language: node_js
node_js:
  - "5.5"
before_script:
  - npm install -g gulp
script: gulp test-all
compiler: clang-3.7
env:
  - CXX=clang-3.7
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - g++-5.3
